/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LopHocSoRouteImport } from './routes/lop-hoc-so'
import { Route as HocSinhRouteImport } from './routes/hoc-sinh'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LopHocSoIndexRouteImport } from './routes/lop-hoc-so.index'
import { Route as HocSinhIndexRouteImport } from './routes/hoc-sinh.index'
import { Route as LopHocSoClassIdRouteImport } from './routes/lop-hoc-so.$classId'
import { Route as HocSinhThongKeHoatDongRouteImport } from './routes/hoc-sinh.thong-ke-hoat-dong'
import { Route as HocSinhNhiemVuRouteImport } from './routes/hoc-sinh.nhiem-vu'
import { Route as HocSinhLopTrucTuyenRouteImport } from './routes/hoc-sinh.lop-truc-tuyen'
import { Route as HocSinhLopBaiGiangRouteImport } from './routes/hoc-sinh.lop-bai-giang'
import { Route as HocSinhLoTrinhRouteImport } from './routes/hoc-sinh.lo-trinh'
import { Route as HocSinhLichSuHocTapRouteImport } from './routes/hoc-sinh.lich-su-hoc-tap'
import { Route as HocSinhKyThiOnTapRouteImport } from './routes/hoc-sinh.ky-thi-on-tap'
import { Route as HocSinhKyThiChinhThucRouteImport } from './routes/hoc-sinh.ky-thi-chinh-thuc'
import { Route as HocSinhHocLieuRouteImport } from './routes/hoc-sinh.hoc-lieu'
import { Route as HocLieuKhoHocLieuRouteImport } from './routes/hoc-lieu.kho-hoc-lieu'
import { Route as HocLieuBaiGiangIndexRouteImport } from './routes/hoc-lieu.bai-giang.index'
import { Route as HocSinhLopLopRouteImport } from './routes/hoc-sinh.lop.$lop'
import { Route as HocLieuBaiGiangTaoMoiRouteImport } from './routes/hoc-lieu.bai-giang.tao-moi'

const LopHocSoRoute = LopHocSoRouteImport.update({
  id: '/lop-hoc-so',
  path: '/lop-hoc-so',
  getParentRoute: () => rootRouteImport,
} as any)
const HocSinhRoute = HocSinhRouteImport.update({
  id: '/hoc-sinh',
  path: '/hoc-sinh',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LopHocSoIndexRoute = LopHocSoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LopHocSoRoute,
} as any)
const HocSinhIndexRoute = HocSinhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HocSinhRoute,
} as any)
const LopHocSoClassIdRoute = LopHocSoClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => LopHocSoRoute,
} as any)
const HocSinhThongKeHoatDongRoute = HocSinhThongKeHoatDongRouteImport.update({
  id: '/thong-ke-hoat-dong',
  path: '/thong-ke-hoat-dong',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocSinhNhiemVuRoute = HocSinhNhiemVuRouteImport.update({
  id: '/nhiem-vu',
  path: '/nhiem-vu',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocSinhLopTrucTuyenRoute = HocSinhLopTrucTuyenRouteImport.update({
  id: '/lop-truc-tuyen',
  path: '/lop-truc-tuyen',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocSinhLopBaiGiangRoute = HocSinhLopBaiGiangRouteImport.update({
  id: '/lop-bai-giang',
  path: '/lop-bai-giang',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocSinhLoTrinhRoute = HocSinhLoTrinhRouteImport.update({
  id: '/lo-trinh',
  path: '/lo-trinh',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocSinhLichSuHocTapRoute = HocSinhLichSuHocTapRouteImport.update({
  id: '/lich-su-hoc-tap',
  path: '/lich-su-hoc-tap',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocSinhKyThiOnTapRoute = HocSinhKyThiOnTapRouteImport.update({
  id: '/ky-thi-on-tap',
  path: '/ky-thi-on-tap',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocSinhKyThiChinhThucRoute = HocSinhKyThiChinhThucRouteImport.update({
  id: '/ky-thi-chinh-thuc',
  path: '/ky-thi-chinh-thuc',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocSinhHocLieuRoute = HocSinhHocLieuRouteImport.update({
  id: '/hoc-lieu',
  path: '/hoc-lieu',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocLieuKhoHocLieuRoute = HocLieuKhoHocLieuRouteImport.update({
  id: '/hoc-lieu/kho-hoc-lieu',
  path: '/hoc-lieu/kho-hoc-lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const HocLieuBaiGiangIndexRoute = HocLieuBaiGiangIndexRouteImport.update({
  id: '/hoc-lieu/bai-giang/',
  path: '/hoc-lieu/bai-giang/',
  getParentRoute: () => rootRouteImport,
} as any)
const HocSinhLopLopRoute = HocSinhLopLopRouteImport.update({
  id: '/lop/$lop',
  path: '/lop/$lop',
  getParentRoute: () => HocSinhRoute,
} as any)
const HocLieuBaiGiangTaoMoiRoute = HocLieuBaiGiangTaoMoiRouteImport.update({
  id: '/hoc-lieu/bai-giang/tao-moi',
  path: '/hoc-lieu/bai-giang/tao-moi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hoc-sinh': typeof HocSinhRouteWithChildren
  '/lop-hoc-so': typeof LopHocSoRouteWithChildren
  '/hoc-lieu/kho-hoc-lieu': typeof HocLieuKhoHocLieuRoute
  '/hoc-sinh/hoc-lieu': typeof HocSinhHocLieuRoute
  '/hoc-sinh/ky-thi-chinh-thuc': typeof HocSinhKyThiChinhThucRoute
  '/hoc-sinh/ky-thi-on-tap': typeof HocSinhKyThiOnTapRoute
  '/hoc-sinh/lich-su-hoc-tap': typeof HocSinhLichSuHocTapRoute
  '/hoc-sinh/lo-trinh': typeof HocSinhLoTrinhRoute
  '/hoc-sinh/lop-bai-giang': typeof HocSinhLopBaiGiangRoute
  '/hoc-sinh/lop-truc-tuyen': typeof HocSinhLopTrucTuyenRoute
  '/hoc-sinh/nhiem-vu': typeof HocSinhNhiemVuRoute
  '/hoc-sinh/thong-ke-hoat-dong': typeof HocSinhThongKeHoatDongRoute
  '/lop-hoc-so/$classId': typeof LopHocSoClassIdRoute
  '/hoc-sinh/': typeof HocSinhIndexRoute
  '/lop-hoc-so/': typeof LopHocSoIndexRoute
  '/hoc-lieu/bai-giang/tao-moi': typeof HocLieuBaiGiangTaoMoiRoute
  '/hoc-sinh/lop/$lop': typeof HocSinhLopLopRoute
  '/hoc-lieu/bai-giang/': typeof HocLieuBaiGiangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hoc-lieu/kho-hoc-lieu': typeof HocLieuKhoHocLieuRoute
  '/hoc-sinh/hoc-lieu': typeof HocSinhHocLieuRoute
  '/hoc-sinh/ky-thi-chinh-thuc': typeof HocSinhKyThiChinhThucRoute
  '/hoc-sinh/ky-thi-on-tap': typeof HocSinhKyThiOnTapRoute
  '/hoc-sinh/lich-su-hoc-tap': typeof HocSinhLichSuHocTapRoute
  '/hoc-sinh/lo-trinh': typeof HocSinhLoTrinhRoute
  '/hoc-sinh/lop-bai-giang': typeof HocSinhLopBaiGiangRoute
  '/hoc-sinh/lop-truc-tuyen': typeof HocSinhLopTrucTuyenRoute
  '/hoc-sinh/nhiem-vu': typeof HocSinhNhiemVuRoute
  '/hoc-sinh/thong-ke-hoat-dong': typeof HocSinhThongKeHoatDongRoute
  '/lop-hoc-so/$classId': typeof LopHocSoClassIdRoute
  '/hoc-sinh': typeof HocSinhIndexRoute
  '/lop-hoc-so': typeof LopHocSoIndexRoute
  '/hoc-lieu/bai-giang/tao-moi': typeof HocLieuBaiGiangTaoMoiRoute
  '/hoc-sinh/lop/$lop': typeof HocSinhLopLopRoute
  '/hoc-lieu/bai-giang': typeof HocLieuBaiGiangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hoc-sinh': typeof HocSinhRouteWithChildren
  '/lop-hoc-so': typeof LopHocSoRouteWithChildren
  '/hoc-lieu/kho-hoc-lieu': typeof HocLieuKhoHocLieuRoute
  '/hoc-sinh/hoc-lieu': typeof HocSinhHocLieuRoute
  '/hoc-sinh/ky-thi-chinh-thuc': typeof HocSinhKyThiChinhThucRoute
  '/hoc-sinh/ky-thi-on-tap': typeof HocSinhKyThiOnTapRoute
  '/hoc-sinh/lich-su-hoc-tap': typeof HocSinhLichSuHocTapRoute
  '/hoc-sinh/lo-trinh': typeof HocSinhLoTrinhRoute
  '/hoc-sinh/lop-bai-giang': typeof HocSinhLopBaiGiangRoute
  '/hoc-sinh/lop-truc-tuyen': typeof HocSinhLopTrucTuyenRoute
  '/hoc-sinh/nhiem-vu': typeof HocSinhNhiemVuRoute
  '/hoc-sinh/thong-ke-hoat-dong': typeof HocSinhThongKeHoatDongRoute
  '/lop-hoc-so/$classId': typeof LopHocSoClassIdRoute
  '/hoc-sinh/': typeof HocSinhIndexRoute
  '/lop-hoc-so/': typeof LopHocSoIndexRoute
  '/hoc-lieu/bai-giang/tao-moi': typeof HocLieuBaiGiangTaoMoiRoute
  '/hoc-sinh/lop/$lop': typeof HocSinhLopLopRoute
  '/hoc-lieu/bai-giang/': typeof HocLieuBaiGiangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hoc-sinh'
    | '/lop-hoc-so'
    | '/hoc-lieu/kho-hoc-lieu'
    | '/hoc-sinh/hoc-lieu'
    | '/hoc-sinh/ky-thi-chinh-thuc'
    | '/hoc-sinh/ky-thi-on-tap'
    | '/hoc-sinh/lich-su-hoc-tap'
    | '/hoc-sinh/lo-trinh'
    | '/hoc-sinh/lop-bai-giang'
    | '/hoc-sinh/lop-truc-tuyen'
    | '/hoc-sinh/nhiem-vu'
    | '/hoc-sinh/thong-ke-hoat-dong'
    | '/lop-hoc-so/$classId'
    | '/hoc-sinh/'
    | '/lop-hoc-so/'
    | '/hoc-lieu/bai-giang/tao-moi'
    | '/hoc-sinh/lop/$lop'
    | '/hoc-lieu/bai-giang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hoc-lieu/kho-hoc-lieu'
    | '/hoc-sinh/hoc-lieu'
    | '/hoc-sinh/ky-thi-chinh-thuc'
    | '/hoc-sinh/ky-thi-on-tap'
    | '/hoc-sinh/lich-su-hoc-tap'
    | '/hoc-sinh/lo-trinh'
    | '/hoc-sinh/lop-bai-giang'
    | '/hoc-sinh/lop-truc-tuyen'
    | '/hoc-sinh/nhiem-vu'
    | '/hoc-sinh/thong-ke-hoat-dong'
    | '/lop-hoc-so/$classId'
    | '/hoc-sinh'
    | '/lop-hoc-so'
    | '/hoc-lieu/bai-giang/tao-moi'
    | '/hoc-sinh/lop/$lop'
    | '/hoc-lieu/bai-giang'
  id:
    | '__root__'
    | '/'
    | '/hoc-sinh'
    | '/lop-hoc-so'
    | '/hoc-lieu/kho-hoc-lieu'
    | '/hoc-sinh/hoc-lieu'
    | '/hoc-sinh/ky-thi-chinh-thuc'
    | '/hoc-sinh/ky-thi-on-tap'
    | '/hoc-sinh/lich-su-hoc-tap'
    | '/hoc-sinh/lo-trinh'
    | '/hoc-sinh/lop-bai-giang'
    | '/hoc-sinh/lop-truc-tuyen'
    | '/hoc-sinh/nhiem-vu'
    | '/hoc-sinh/thong-ke-hoat-dong'
    | '/lop-hoc-so/$classId'
    | '/hoc-sinh/'
    | '/lop-hoc-so/'
    | '/hoc-lieu/bai-giang/tao-moi'
    | '/hoc-sinh/lop/$lop'
    | '/hoc-lieu/bai-giang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HocSinhRoute: typeof HocSinhRouteWithChildren
  LopHocSoRoute: typeof LopHocSoRouteWithChildren
  HocLieuKhoHocLieuRoute: typeof HocLieuKhoHocLieuRoute
  HocLieuBaiGiangTaoMoiRoute: typeof HocLieuBaiGiangTaoMoiRoute
  HocLieuBaiGiangIndexRoute: typeof HocLieuBaiGiangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lop-hoc-so': {
      id: '/lop-hoc-so'
      path: '/lop-hoc-so'
      fullPath: '/lop-hoc-so'
      preLoaderRoute: typeof LopHocSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-sinh': {
      id: '/hoc-sinh'
      path: '/hoc-sinh'
      fullPath: '/hoc-sinh'
      preLoaderRoute: typeof HocSinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lop-hoc-so/': {
      id: '/lop-hoc-so/'
      path: '/'
      fullPath: '/lop-hoc-so/'
      preLoaderRoute: typeof LopHocSoIndexRouteImport
      parentRoute: typeof LopHocSoRoute
    }
    '/hoc-sinh/': {
      id: '/hoc-sinh/'
      path: '/'
      fullPath: '/hoc-sinh/'
      preLoaderRoute: typeof HocSinhIndexRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/lop-hoc-so/$classId': {
      id: '/lop-hoc-so/$classId'
      path: '/$classId'
      fullPath: '/lop-hoc-so/$classId'
      preLoaderRoute: typeof LopHocSoClassIdRouteImport
      parentRoute: typeof LopHocSoRoute
    }
    '/hoc-sinh/thong-ke-hoat-dong': {
      id: '/hoc-sinh/thong-ke-hoat-dong'
      path: '/thong-ke-hoat-dong'
      fullPath: '/hoc-sinh/thong-ke-hoat-dong'
      preLoaderRoute: typeof HocSinhThongKeHoatDongRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-sinh/nhiem-vu': {
      id: '/hoc-sinh/nhiem-vu'
      path: '/nhiem-vu'
      fullPath: '/hoc-sinh/nhiem-vu'
      preLoaderRoute: typeof HocSinhNhiemVuRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-sinh/lop-truc-tuyen': {
      id: '/hoc-sinh/lop-truc-tuyen'
      path: '/lop-truc-tuyen'
      fullPath: '/hoc-sinh/lop-truc-tuyen'
      preLoaderRoute: typeof HocSinhLopTrucTuyenRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-sinh/lop-bai-giang': {
      id: '/hoc-sinh/lop-bai-giang'
      path: '/lop-bai-giang'
      fullPath: '/hoc-sinh/lop-bai-giang'
      preLoaderRoute: typeof HocSinhLopBaiGiangRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-sinh/lo-trinh': {
      id: '/hoc-sinh/lo-trinh'
      path: '/lo-trinh'
      fullPath: '/hoc-sinh/lo-trinh'
      preLoaderRoute: typeof HocSinhLoTrinhRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-sinh/lich-su-hoc-tap': {
      id: '/hoc-sinh/lich-su-hoc-tap'
      path: '/lich-su-hoc-tap'
      fullPath: '/hoc-sinh/lich-su-hoc-tap'
      preLoaderRoute: typeof HocSinhLichSuHocTapRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-sinh/ky-thi-on-tap': {
      id: '/hoc-sinh/ky-thi-on-tap'
      path: '/ky-thi-on-tap'
      fullPath: '/hoc-sinh/ky-thi-on-tap'
      preLoaderRoute: typeof HocSinhKyThiOnTapRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-sinh/ky-thi-chinh-thuc': {
      id: '/hoc-sinh/ky-thi-chinh-thuc'
      path: '/ky-thi-chinh-thuc'
      fullPath: '/hoc-sinh/ky-thi-chinh-thuc'
      preLoaderRoute: typeof HocSinhKyThiChinhThucRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-sinh/hoc-lieu': {
      id: '/hoc-sinh/hoc-lieu'
      path: '/hoc-lieu'
      fullPath: '/hoc-sinh/hoc-lieu'
      preLoaderRoute: typeof HocSinhHocLieuRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-lieu/kho-hoc-lieu': {
      id: '/hoc-lieu/kho-hoc-lieu'
      path: '/hoc-lieu/kho-hoc-lieu'
      fullPath: '/hoc-lieu/kho-hoc-lieu'
      preLoaderRoute: typeof HocLieuKhoHocLieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-lieu/bai-giang/': {
      id: '/hoc-lieu/bai-giang/'
      path: '/hoc-lieu/bai-giang'
      fullPath: '/hoc-lieu/bai-giang/'
      preLoaderRoute: typeof HocLieuBaiGiangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-sinh/lop/$lop': {
      id: '/hoc-sinh/lop/$lop'
      path: '/lop/$lop'
      fullPath: '/hoc-sinh/lop/$lop'
      preLoaderRoute: typeof HocSinhLopLopRouteImport
      parentRoute: typeof HocSinhRoute
    }
    '/hoc-lieu/bai-giang/tao-moi': {
      id: '/hoc-lieu/bai-giang/tao-moi'
      path: '/hoc-lieu/bai-giang/tao-moi'
      fullPath: '/hoc-lieu/bai-giang/tao-moi'
      preLoaderRoute: typeof HocLieuBaiGiangTaoMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HocSinhRouteChildren {
  HocSinhHocLieuRoute: typeof HocSinhHocLieuRoute
  HocSinhKyThiChinhThucRoute: typeof HocSinhKyThiChinhThucRoute
  HocSinhKyThiOnTapRoute: typeof HocSinhKyThiOnTapRoute
  HocSinhLichSuHocTapRoute: typeof HocSinhLichSuHocTapRoute
  HocSinhLoTrinhRoute: typeof HocSinhLoTrinhRoute
  HocSinhLopBaiGiangRoute: typeof HocSinhLopBaiGiangRoute
  HocSinhLopTrucTuyenRoute: typeof HocSinhLopTrucTuyenRoute
  HocSinhNhiemVuRoute: typeof HocSinhNhiemVuRoute
  HocSinhThongKeHoatDongRoute: typeof HocSinhThongKeHoatDongRoute
  HocSinhIndexRoute: typeof HocSinhIndexRoute
  HocSinhLopLopRoute: typeof HocSinhLopLopRoute
}

const HocSinhRouteChildren: HocSinhRouteChildren = {
  HocSinhHocLieuRoute: HocSinhHocLieuRoute,
  HocSinhKyThiChinhThucRoute: HocSinhKyThiChinhThucRoute,
  HocSinhKyThiOnTapRoute: HocSinhKyThiOnTapRoute,
  HocSinhLichSuHocTapRoute: HocSinhLichSuHocTapRoute,
  HocSinhLoTrinhRoute: HocSinhLoTrinhRoute,
  HocSinhLopBaiGiangRoute: HocSinhLopBaiGiangRoute,
  HocSinhLopTrucTuyenRoute: HocSinhLopTrucTuyenRoute,
  HocSinhNhiemVuRoute: HocSinhNhiemVuRoute,
  HocSinhThongKeHoatDongRoute: HocSinhThongKeHoatDongRoute,
  HocSinhIndexRoute: HocSinhIndexRoute,
  HocSinhLopLopRoute: HocSinhLopLopRoute,
}

const HocSinhRouteWithChildren =
  HocSinhRoute._addFileChildren(HocSinhRouteChildren)

interface LopHocSoRouteChildren {
  LopHocSoClassIdRoute: typeof LopHocSoClassIdRoute
  LopHocSoIndexRoute: typeof LopHocSoIndexRoute
}

const LopHocSoRouteChildren: LopHocSoRouteChildren = {
  LopHocSoClassIdRoute: LopHocSoClassIdRoute,
  LopHocSoIndexRoute: LopHocSoIndexRoute,
}

const LopHocSoRouteWithChildren = LopHocSoRoute._addFileChildren(
  LopHocSoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HocSinhRoute: HocSinhRouteWithChildren,
  LopHocSoRoute: LopHocSoRouteWithChildren,
  HocLieuKhoHocLieuRoute: HocLieuKhoHocLieuRoute,
  HocLieuBaiGiangTaoMoiRoute: HocLieuBaiGiangTaoMoiRoute,
  HocLieuBaiGiangIndexRoute: HocLieuBaiGiangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
