/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LopHocSoRouteImport } from './routes/lop-hoc-so'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LopHocSoIndexRouteImport } from './routes/lop-hoc-so.index'
import { Route as LopHocSoClassIdRouteImport } from './routes/lop-hoc-so.$classId'
import { Route as HocLieuKhoHocLieuRouteImport } from './routes/hoc-lieu.kho-hoc-lieu'
import { Route as HocLieuBaiGiangIndexRouteImport } from './routes/hoc-lieu.bai-giang.index'
import { Route as HocLieuBaiGiangTaoMoiRouteImport } from './routes/hoc-lieu.bai-giang.tao-moi'

const LopHocSoRoute = LopHocSoRouteImport.update({
  id: '/lop-hoc-so',
  path: '/lop-hoc-so',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LopHocSoIndexRoute = LopHocSoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LopHocSoRoute,
} as any)
const LopHocSoClassIdRoute = LopHocSoClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => LopHocSoRoute,
} as any)
const HocLieuKhoHocLieuRoute = HocLieuKhoHocLieuRouteImport.update({
  id: '/hoc-lieu/kho-hoc-lieu',
  path: '/hoc-lieu/kho-hoc-lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const HocLieuBaiGiangIndexRoute = HocLieuBaiGiangIndexRouteImport.update({
  id: '/hoc-lieu/bai-giang/',
  path: '/hoc-lieu/bai-giang/',
  getParentRoute: () => rootRouteImport,
} as any)
const HocLieuBaiGiangTaoMoiRoute = HocLieuBaiGiangTaoMoiRouteImport.update({
  id: '/hoc-lieu/bai-giang/tao-moi',
  path: '/hoc-lieu/bai-giang/tao-moi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lop-hoc-so': typeof LopHocSoRouteWithChildren
  '/hoc-lieu/kho-hoc-lieu': typeof HocLieuKhoHocLieuRoute
  '/lop-hoc-so/$classId': typeof LopHocSoClassIdRoute
  '/lop-hoc-so/': typeof LopHocSoIndexRoute
  '/hoc-lieu/bai-giang/tao-moi': typeof HocLieuBaiGiangTaoMoiRoute
  '/hoc-lieu/bai-giang/': typeof HocLieuBaiGiangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hoc-lieu/kho-hoc-lieu': typeof HocLieuKhoHocLieuRoute
  '/lop-hoc-so/$classId': typeof LopHocSoClassIdRoute
  '/lop-hoc-so': typeof LopHocSoIndexRoute
  '/hoc-lieu/bai-giang/tao-moi': typeof HocLieuBaiGiangTaoMoiRoute
  '/hoc-lieu/bai-giang': typeof HocLieuBaiGiangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lop-hoc-so': typeof LopHocSoRouteWithChildren
  '/hoc-lieu/kho-hoc-lieu': typeof HocLieuKhoHocLieuRoute
  '/lop-hoc-so/$classId': typeof LopHocSoClassIdRoute
  '/lop-hoc-so/': typeof LopHocSoIndexRoute
  '/hoc-lieu/bai-giang/tao-moi': typeof HocLieuBaiGiangTaoMoiRoute
  '/hoc-lieu/bai-giang/': typeof HocLieuBaiGiangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lop-hoc-so'
    | '/hoc-lieu/kho-hoc-lieu'
    | '/lop-hoc-so/$classId'
    | '/lop-hoc-so/'
    | '/hoc-lieu/bai-giang/tao-moi'
    | '/hoc-lieu/bai-giang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hoc-lieu/kho-hoc-lieu'
    | '/lop-hoc-so/$classId'
    | '/lop-hoc-so'
    | '/hoc-lieu/bai-giang/tao-moi'
    | '/hoc-lieu/bai-giang'
  id:
    | '__root__'
    | '/'
    | '/lop-hoc-so'
    | '/hoc-lieu/kho-hoc-lieu'
    | '/lop-hoc-so/$classId'
    | '/lop-hoc-so/'
    | '/hoc-lieu/bai-giang/tao-moi'
    | '/hoc-lieu/bai-giang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LopHocSoRoute: typeof LopHocSoRouteWithChildren
  HocLieuKhoHocLieuRoute: typeof HocLieuKhoHocLieuRoute
  HocLieuBaiGiangTaoMoiRoute: typeof HocLieuBaiGiangTaoMoiRoute
  HocLieuBaiGiangIndexRoute: typeof HocLieuBaiGiangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lop-hoc-so': {
      id: '/lop-hoc-so'
      path: '/lop-hoc-so'
      fullPath: '/lop-hoc-so'
      preLoaderRoute: typeof LopHocSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lop-hoc-so/': {
      id: '/lop-hoc-so/'
      path: '/'
      fullPath: '/lop-hoc-so/'
      preLoaderRoute: typeof LopHocSoIndexRouteImport
      parentRoute: typeof LopHocSoRoute
    }
    '/lop-hoc-so/$classId': {
      id: '/lop-hoc-so/$classId'
      path: '/$classId'
      fullPath: '/lop-hoc-so/$classId'
      preLoaderRoute: typeof LopHocSoClassIdRouteImport
      parentRoute: typeof LopHocSoRoute
    }
    '/hoc-lieu/kho-hoc-lieu': {
      id: '/hoc-lieu/kho-hoc-lieu'
      path: '/hoc-lieu/kho-hoc-lieu'
      fullPath: '/hoc-lieu/kho-hoc-lieu'
      preLoaderRoute: typeof HocLieuKhoHocLieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-lieu/bai-giang/': {
      id: '/hoc-lieu/bai-giang/'
      path: '/hoc-lieu/bai-giang'
      fullPath: '/hoc-lieu/bai-giang/'
      preLoaderRoute: typeof HocLieuBaiGiangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-lieu/bai-giang/tao-moi': {
      id: '/hoc-lieu/bai-giang/tao-moi'
      path: '/hoc-lieu/bai-giang/tao-moi'
      fullPath: '/hoc-lieu/bai-giang/tao-moi'
      preLoaderRoute: typeof HocLieuBaiGiangTaoMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LopHocSoRouteChildren {
  LopHocSoClassIdRoute: typeof LopHocSoClassIdRoute
  LopHocSoIndexRoute: typeof LopHocSoIndexRoute
}

const LopHocSoRouteChildren: LopHocSoRouteChildren = {
  LopHocSoClassIdRoute: LopHocSoClassIdRoute,
  LopHocSoIndexRoute: LopHocSoIndexRoute,
}

const LopHocSoRouteWithChildren = LopHocSoRoute._addFileChildren(
  LopHocSoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LopHocSoRoute: LopHocSoRouteWithChildren,
  HocLieuKhoHocLieuRoute: HocLieuKhoHocLieuRoute,
  HocLieuBaiGiangTaoMoiRoute: HocLieuBaiGiangTaoMoiRoute,
  HocLieuBaiGiangIndexRoute: HocLieuBaiGiangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
